### ISSUE TITLE
Use readthedocs Docker image in CI

### ISSUE THREAD

**Issue by wtraylor** [wtraylor/modular_megafauna_model#34]
The CI step "doxygen" in `.gitlab-ci.yml` currently runs with the `ubuntu:latest` Docker image. It needs various dependencies which take time and resources during CI.

It would make more sense to use the Docker image [`readthedocs/build:latest`](https://hub.docker.com/r/readthedocs/build/) because that already has almost everything packaged (except `cmake`), *and* it is also the one used by Read the Docs to build the documentation (compare the [docs](https://docs.readthedocs.io/en/stable/builds.html)). So the CI can catch potential issues before the release.

Unfortunately, the "latest" (7.0) does not contain the necessary Doxygen version (1.8.16), and the pipeline fails with it. ("testing", 8.0, seems to have a bug because `conda` is not available, which is required to install `cmake`.)

As soon as `readthedocs/build:latest` is updated to Ubuntu 20.04, we can use it in `.gitlab-ci.yml` like so:

```yaml
doxygen:
  image: readthedocs/build:latest
  stage: build
  before_script:
    - conda install --yes cmake
  script:
    - mkdir --parents build
    - cd build
    - cmake
      -DSTOP_DOXYGEN_ON_WARNING=ON
      -DBUILD_TESTING=OFF
      -DBUILD_DEMO_SIMULATOR=OFF
      -DBUILD_DOC=ON ..
    - make --jobs=6 megafauna_docs
  artifacts:
    paths:
      - build/docs/html/
```
